#!/sbin/openrc-run
# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

start() {
	ebegin "Starting newsd"
	       start-stop-daemon --start --quiet \
                             --exec /usr/sbin/newsd -- -c /etc/newsd.conf
	eend $?
}

stop() {
	ebegin "Stopping newsd"
	       start-stop-daemon --stop --quiet \
                             --exec /usr/sbin/newsd
	eend $?
}
